version: "3.1"
services:
    db:
        build: ./db/.
        image: postgres_db
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: password123
            POSTGRES_DB: osm
            POSTGRES_USER: admin
    # node:
    #     build: "./node_api"
    #     ports:
    #         - "9000:9000"
    #     volumes:
    #         - ./node_api:/usr/src/app
    #     working_dir: /usr/src/app
    #     command: npm run dev
